#! /bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -t 1-20
#$ -q all.q
#$ -pe mpi_smp 4
#$ -e /home2/data/Projects/Emotional-BS/share/10_preprocessing/cluster_temp_files/c-pac_2013_10_31_00_14_51.err
#$ -o /home2/data/Projects/Emotional-BS/share/10_preprocessing/cluster_temp_files/c-pac_2013_10_31_00_14_51.out
source ~/.bashrc
python -c "import CPAC; CPAC.pipeline.cpac_pipeline.run(\"20_run/run_config.yaml\" , \"20_run/CPAC_subject_list.yml\", \"$SGE_TASK_ID\" , \"/home2/data/Projects/Emotional-BS/share/10_preprocessing/cluster_temp_files/strategies.obj\", \"None\" , \"/home2/data/Projects/ABIDE_Initiative/CPAC/abide/tse/ROI_list_timeseriesExtraction.txt\", \"None\", \"None\") " 
